package net.teddy0008.ad_extendra.datagen;

import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.minecraftforge.common.Tags;
import net.minecraftforge.common.data.BlockTagsProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.teddy0008.ad_extendra.Main;
import net.teddy0008.ad_extendra.block.ModBlocks;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagGenerator extends BlockTagsProvider {

    public ModBlockTagGenerator(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, Main.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        // this.tag(ModTags.Blocks.TAG).add(ModBlocks.BLOCK.get()).addTags(Tags.Blocks.TAG);
        this.tag(BlockTags.NEEDS_DIAMOND_TOOL)
                // Jupiter
                .add(ModBlocks.JUPERIUM_BLOCK.get())
                .add(ModBlocks.JUPITER_JUPERIUM_ORE.get())
                .add(ModBlocks.RAW_JUPERIUM_BLOCK.get())
                .add(ModBlocks.JUPERIUM_PLATING.get())
                .add(ModBlocks.JUPERIUM_PLATING_STAIRS.get())
                .add(ModBlocks.JUPERIUM_PLATING_SLAB.get())
                .add(ModBlocks.JUPERIUM_PILLAR.get())
                .add(ModBlocks.GLOWING_JUPERIUM_PILLAR.get())
                .add(ModBlocks.JUPERIUM_PLATING_BUTTON.get())
                .add(ModBlocks.JUPERIUM_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.JUPERIUM_SLIDING_DOOR.get())

                // Saturn
                .add(ModBlocks.SATURLYTE_BLOCK.get())
                .add(ModBlocks.SATURN_SATURLYTE_ORE.get())
                .add(ModBlocks.RAW_SATURLYTE_BLOCK.get())
                .add(ModBlocks.SATURLYTE_PLATING.get())
                .add(ModBlocks.SATURLYTE_PLATING_STAIRS.get())
                .add(ModBlocks.SATURLYTE_PLATING_SLAB.get())
                .add(ModBlocks.SATURLYTE_PILLAR.get())
                .add(ModBlocks.GLOWING_SATURLYTE_PILLAR.get())
                .add(ModBlocks.SATURLYTE_PLATING_BUTTON.get())
                .add(ModBlocks.SATURLYTE_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.SATURLYTE_SLIDING_DOOR.get());
        this.tag(Tags.Blocks.NEEDS_NETHERITE_TOOL)
                // Uranus
                .add(ModBlocks.URANIUM_BLOCK.get())
                .add(ModBlocks.URANUS_URANIUM_ORE.get())
                .add(ModBlocks.RAW_URANIUM_BLOCK.get())
                .add(ModBlocks.URANIUM_PLATING.get())
                .add(ModBlocks.URANIUM_PLATING_STAIRS.get())
                .add(ModBlocks.URANIUM_PLATING_SLAB.get())
                .add(ModBlocks.URANIUM_PILLAR.get())
                .add(ModBlocks.GLOWING_URANIUM_PILLAR.get())
                .add(ModBlocks.URANIUM_PLATING_BUTTON.get())
                .add(ModBlocks.URANIUM_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.URANIUM_SLIDING_DOOR.get())

                // Neptune
                .add(ModBlocks.NEPTUNIUM_BLOCK.get())
                .add(ModBlocks.NEPTUNE_NEPTUNIUM_ORE.get())
                .add(ModBlocks.RAW_NEPTUNIUM_BLOCK.get())
                .add(ModBlocks.NEPTUNIUM_PLATING.get())
                .add(ModBlocks.NEPTUNIUM_PLATING_STAIRS.get())
                .add(ModBlocks.NEPTUNIUM_PLATING_SLAB.get())
                .add(ModBlocks.NEPTUNIUM_PILLAR.get())
                .add(ModBlocks.GLOWING_NEPTUNIUM_PILLAR.get())
                .add(ModBlocks.NEPTUNIUM_PLATING_BUTTON.get())
                .add(ModBlocks.NEPTUNIUM_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.NEPTUNIUM_SLIDING_DOOR.get())

                // Orcus
                .add(ModBlocks.RADIUM_BLOCK.get())
                .add(ModBlocks.ORCUS_RADIUM_ORE.get())
                .add(ModBlocks.RAW_RADIUM_BLOCK.get())
                .add(ModBlocks.RADIUM_PLATING.get())
                .add(ModBlocks.RADIUM_PLATING_STAIRS.get())
                .add(ModBlocks.RADIUM_PLATING_SLAB.get())
                .add(ModBlocks.RADIUM_PILLAR.get())
                .add(ModBlocks.GLOWING_RADIUM_PILLAR.get())
                .add(ModBlocks.RADIUM_PLATING_BUTTON.get())
                .add(ModBlocks.RADIUM_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.RADIUM_SLIDING_DOOR.get())

                // Pluto
                .add(ModBlocks.PLUTONIUM_BLOCK.get())
                .add(ModBlocks.PLUTO_PLUTONIUM_ORE.get())
                .add(ModBlocks.RAW_PLUTONIUM_BLOCK.get())
                .add(ModBlocks.PLUTONIUM_PLATING.get())
                .add(ModBlocks.PLUTONIUM_PLATING_STAIRS.get())
                .add(ModBlocks.PLUTONIUM_PLATING_SLAB.get())
                .add(ModBlocks.PLUTONIUM_PILLAR.get())
                .add(ModBlocks.GLOWING_PLUTONIUM_PILLAR.get())
                .add(ModBlocks.PLUTONIUM_PLATING_BUTTON.get())
                .add(ModBlocks.PLUTONIUM_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.PLUTONIUM_SLIDING_DOOR.get())

                // Sedna
                .add(ModBlocks.ELECTROLYTE_BLOCK.get())
                .add(ModBlocks.SEDNA_ELECTROLYTE_ORE.get())
                .add(ModBlocks.RAW_ELECTROLYTE_BLOCK.get())
                .add(ModBlocks.ELECTROLYTE_PLATING.get())
                .add(ModBlocks.ELECTROLYTE_PLATING_STAIRS.get())
                .add(ModBlocks.ELECTROLYTE_PLATING_SLAB.get())
                .add(ModBlocks.ELECTROLYTE_PILLAR.get())
                .add(ModBlocks.GLOWING_ELECTROLYTE_PILLAR.get())
                .add(ModBlocks.ELECTROLYTE_PLATING_BUTTON.get())
                .add(ModBlocks.ELECTROLYTE_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.ELECTROLYTE_SLIDING_DOOR.get());
        this.tag(BlockTags.NEEDS_STONE_TOOL)
                .add(ModBlocks.JUPITER_COAL_ORE.get())
                .add(ModBlocks.CERES_IRON_ORE.get())
                .add(ModBlocks.CERES_COPPER_ORE.get())
                .add(ModBlocks.SATURN_COAL_ORE.get())
                .add(ModBlocks.URANUS_IRON_ORE.get())
                .add(ModBlocks.NEPTUNE_COAL_ORE.get())
                .add(ModBlocks.NEPTUNE_IRON_ORE.get())
                .add(ModBlocks.NEPTUNE_COPPER_ORE.get())
                .add(ModBlocks.ORCUS_IRON_ORE.get())
                .add(ModBlocks.ORCUS_COPPER_ORE.get())
                .add(ModBlocks.HAUMEA_IRON_ORE.get())
                .add(ModBlocks.HAUMEA_COPPER_ORE.get())
                .add(ModBlocks.QUAOAR_IRON_ORE.get())
                .add(ModBlocks.QUAOAR_COPPER_ORE.get())
                .add(ModBlocks.MAKEMAKE_IRON_ORE.get())
                .add(ModBlocks.MAKEMAKE_COPPER_ORE.get())
                .add(ModBlocks.GONGGONG_IRON_ORE.get())
                .add(ModBlocks.GONGGONG_COPPER_ORE.get())
                .add(ModBlocks.ERIS_IRON_ORE.get())
                .add(ModBlocks.ERIS_COPPER_ORE.get())
                .add(ModBlocks.SEDNA_IRON_ORE.get())
                .add(ModBlocks.SEDNA_COPPER_ORE.get())
                .add(ModBlocks.B_IRON_ORE.get());
        this.tag(BlockTags.NEEDS_IRON_TOOL)
                .add(ModBlocks.JUPITER_DIAMOND_ORE.get())
                .add(ModBlocks.JUPITER_GOLD_ORE.get())
                .add(ModBlocks.SATURN_DIAMOND_ORE.get())
                .add(ModBlocks.SATURN_GOLD_ORE.get())
                .add(ModBlocks.URANUS_DIAMOND_ORE.get())
                .add(ModBlocks.PLUTO_DIAMOND_ORE.get())
                .add(ModBlocks.PLUTO_GOLD_ORE.get())
                .add(ModBlocks.B_DIAMOND_ORE.get())
                .add(ModBlocks.B_EMERALD_ORE.get())
                .add(ModBlocks.B_REDSTONE_ORE.get());
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE)
                // Jupiter
                .add(ModBlocks.JUPERIUM_BLOCK.get())
                .add(ModBlocks.JUPITER_JUPERIUM_ORE.get())
                .add(ModBlocks.RAW_JUPERIUM_BLOCK.get())
                .add(ModBlocks.JUPERIUM_PLATING.get())
                .add(ModBlocks.JUPERIUM_PLATING_STAIRS.get())
                .add(ModBlocks.JUPERIUM_PLATING_SLAB.get())
                .add(ModBlocks.JUPERIUM_PILLAR.get())
                .add(ModBlocks.GLOWING_JUPERIUM_PILLAR.get())
                .add(ModBlocks.JUPERIUM_PLATING_BUTTON.get())
                .add(ModBlocks.JUPERIUM_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.JUPERIUM_SLIDING_DOOR.get())
                .add(ModBlocks.JUPITER_STONE.get())
                .add(ModBlocks.JUPITER_STONE_STAIRS.get())
                .add(ModBlocks.JUPITER_STONE_SLAB.get())
                .add(ModBlocks.JUPITER_COBBLESTONE.get())
                .add(ModBlocks.JUPITER_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.JUPITER_COBBLESTONE_SLAB.get())
                .add(ModBlocks.JUPITER_STONE_BRICKS.get())
                .add(ModBlocks.JUPITER_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.JUPITER_STONE_BRICK_SLAB.get())
                .add(ModBlocks.JUPITER_STONE_BRICK_WALL.get())
                .add(ModBlocks.CRACKED_JUPITER_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_JUPITER_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_JUPITER_STONE_STAIRS.get())
                .add(ModBlocks.CHISELED_JUPITER_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_JUPITER_STONE.get())
                .add(ModBlocks.POLISHED_JUPITER_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_JUPITER_STONE_SLAB.get())
                .add(ModBlocks.JUPITER_PILLAR.get())
                .add(ModBlocks.JUPITER_COAL_ORE.get())
                .add(ModBlocks.JUPITER_DIAMOND_ORE.get())
                .add(ModBlocks.JUPITER_GOLD_ORE.get())
                
                // Ceres
                .add(ModBlocks.CERES_STONE.get())
                .add(ModBlocks.CERES_STONE_STAIRS.get())
                .add(ModBlocks.CERES_STONE_SLAB.get())
                .add(ModBlocks.CERES_COBBLESTONE.get())
                .add(ModBlocks.CERES_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.CERES_COBBLESTONE_SLAB.get())
                .add(ModBlocks.CERES_STONE_BRICKS.get())
                .add(ModBlocks.CERES_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.CERES_STONE_BRICK_SLAB.get())
                .add(ModBlocks.CERES_STONE_BRICK_WALL.get())
                .add(ModBlocks.CRACKED_CERES_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_CERES_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_CERES_STONE_STAIRS.get())
                .add(ModBlocks.CHISELED_CERES_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_CERES_STONE.get())
                .add(ModBlocks.POLISHED_CERES_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_CERES_STONE_SLAB.get())
                .add(ModBlocks.CERES_PILLAR.get())
                .add(ModBlocks.CERES_COPPER_ORE.get())
                .add(ModBlocks.CERES_IRON_ORE.get())

                // Saturn
                .add(ModBlocks.SATURLYTE_BLOCK.get())
                .add(ModBlocks.SATURN_SATURLYTE_ORE.get())
                .add(ModBlocks.RAW_SATURLYTE_BLOCK.get())
                .add(ModBlocks.SATURLYTE_PLATING.get())
                .add(ModBlocks.SATURLYTE_PLATING_STAIRS.get())
                .add(ModBlocks.SATURLYTE_PLATING_SLAB.get())
                .add(ModBlocks.SATURLYTE_PILLAR.get())
                .add(ModBlocks.GLOWING_SATURLYTE_PILLAR.get())
                .add(ModBlocks.SATURLYTE_PLATING_BUTTON.get())
                .add(ModBlocks.SATURLYTE_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.SATURLYTE_SLIDING_DOOR.get())
                .add(ModBlocks.SATURN_STONE.get())
                .add(ModBlocks.SATURN_STONE_STAIRS.get())
                .add(ModBlocks.SATURN_STONE_SLAB.get())
                .add(ModBlocks.SATURN_COBBLESTONE.get())
                .add(ModBlocks.SATURN_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.SATURN_COBBLESTONE_SLAB.get())
                .add(ModBlocks.SATURN_STONE_BRICKS.get())
                .add(ModBlocks.SATURN_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.SATURN_STONE_BRICK_SLAB.get())
                .add(ModBlocks.SATURN_STONE_BRICK_WALL.get())
                .add(ModBlocks.CRACKED_SATURN_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_SATURN_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_SATURN_STONE_STAIRS.get())
                .add(ModBlocks.CHISELED_SATURN_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_SATURN_STONE.get())
                .add(ModBlocks.POLISHED_SATURN_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_SATURN_STONE_SLAB.get())
                .add(ModBlocks.SATURN_PILLAR.get())
                .add(ModBlocks.SATURN_COAL_ORE.get())
                .add(ModBlocks.SATURN_DIAMOND_ORE.get())
                .add(ModBlocks.SATURN_GOLD_ORE.get())
                .add(ModBlocks.SATURN_ICE.get())

                // Uranus
                .add(ModBlocks.URANIUM_BLOCK.get())
                .add(ModBlocks.URANUS_URANIUM_ORE.get())
                .add(ModBlocks.RAW_URANIUM_BLOCK.get())
                .add(ModBlocks.URANIUM_PLATING.get())
                .add(ModBlocks.URANIUM_PLATING_STAIRS.get())
                .add(ModBlocks.URANIUM_PLATING_SLAB.get())
                .add(ModBlocks.URANIUM_PILLAR.get())
                .add(ModBlocks.GLOWING_URANIUM_PILLAR.get())
                .add(ModBlocks.URANIUM_PLATING_BUTTON.get())
                .add(ModBlocks.URANIUM_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.URANIUM_SLIDING_DOOR.get())
                .add(ModBlocks.URANUS_ICE_SHARD_ORE.get())
                .add(ModBlocks.URANUS_STONE.get())
                .add(ModBlocks.URANUS_STONE_STAIRS.get())
                .add(ModBlocks.URANUS_STONE_SLAB.get())
                .add(ModBlocks.URANUS_COBBLESTONE.get())
                .add(ModBlocks.URANUS_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.URANUS_COBBLESTONE_SLAB.get())
                .add(ModBlocks.URANUS_STONE_BRICKS.get())
                .add(ModBlocks.URANUS_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.URANUS_STONE_BRICK_SLAB.get())
                .add(ModBlocks.URANUS_STONE_BRICK_WALL.get())
                .add(ModBlocks.CRACKED_URANUS_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_URANUS_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_URANUS_STONE_STAIRS.get())
                .add(ModBlocks.CHISELED_URANUS_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_URANUS_STONE.get())
                .add(ModBlocks.POLISHED_URANUS_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_URANUS_STONE_SLAB.get())
                .add(ModBlocks.URANUS_PILLAR.get())
                .add(ModBlocks.URANUS_DIAMOND_ORE.get())
                .add(ModBlocks.URANUS_IRON_ORE.get())
                .add(ModBlocks.URANUS_LAPIS_ORE.get())
                .add(ModBlocks.SLUSHY_ICE.get())
                .add(ModBlocks.PACKED_SLUSHY_ICE.get())

                // Neptune
                .add(ModBlocks.NEPTUNIUM_BLOCK.get())
                .add(ModBlocks.NEPTUNE_NEPTUNIUM_ORE.get())
                .add(ModBlocks.RAW_NEPTUNIUM_BLOCK.get())
                .add(ModBlocks.NEPTUNIUM_PLATING.get())
                .add(ModBlocks.NEPTUNIUM_PLATING_STAIRS.get())
                .add(ModBlocks.NEPTUNIUM_PLATING_SLAB.get())
                .add(ModBlocks.NEPTUNIUM_PILLAR.get())
                .add(ModBlocks.GLOWING_NEPTUNIUM_PILLAR.get())
                .add(ModBlocks.NEPTUNIUM_PLATING_BUTTON.get())
                .add(ModBlocks.NEPTUNIUM_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.NEPTUNIUM_SLIDING_DOOR.get())
                .add(ModBlocks.NEPTUNE_STONE.get())
                .add(ModBlocks.NEPTUNE_STONE_STAIRS.get())
                .add(ModBlocks.NEPTUNE_STONE_SLAB.get())
                .add(ModBlocks.NEPTUNE_COBBLESTONE.get())
                .add(ModBlocks.NEPTUNE_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.NEPTUNE_COBBLESTONE_SLAB.get())
                .add(ModBlocks.NEPTUNE_STONE_BRICKS.get())
                .add(ModBlocks.NEPTUNE_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.NEPTUNE_STONE_BRICK_SLAB.get())
                .add(ModBlocks.NEPTUNE_STONE_BRICK_WALL.get())
                .add(ModBlocks.CRACKED_NEPTUNE_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_NEPTUNE_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_NEPTUNE_STONE_STAIRS.get())
                .add(ModBlocks.CHISELED_NEPTUNE_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_NEPTUNE_STONE.get())
                .add(ModBlocks.POLISHED_NEPTUNE_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_NEPTUNE_STONE_SLAB.get())
                .add(ModBlocks.NEPTUNE_PILLAR.get())
                .add(ModBlocks.NEPTUNE_COAL_ORE.get())
                .add(ModBlocks.NEPTUNE_COPPER_ORE.get())
                .add(ModBlocks.NEPTUNE_IRON_ORE.get())

                // Orcus
                .add(ModBlocks.RADIUM_BLOCK.get())
                .add(ModBlocks.RAW_RADIUM_BLOCK.get())
                .add(ModBlocks.RADIUM_PLATING.get())
                .add(ModBlocks.RADIUM_PLATING_STAIRS.get())
                .add(ModBlocks.RADIUM_PLATING_SLAB.get())
                .add(ModBlocks.RADIUM_PILLAR.get())
                .add(ModBlocks.GLOWING_RADIUM_PILLAR.get())
                .add(ModBlocks.RADIUM_PLATING_BUTTON.get())
                .add(ModBlocks.RADIUM_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.RADIUM_SLIDING_DOOR.get())
                .add(ModBlocks.ORCUS_STONE.get())
                .add(ModBlocks.ORCUS_STONE_STAIRS.get())
                .add(ModBlocks.ORCUS_STONE_SLAB.get())
                .add(ModBlocks.ORCUS_COBBLESTONE.get())
                .add(ModBlocks.ORCUS_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.ORCUS_COBBLESTONE_SLAB.get())
                .add(ModBlocks.ORCUS_STONE_BRICKS.get())
                .add(ModBlocks.ORCUS_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.ORCUS_STONE_BRICK_SLAB.get())
                .add(ModBlocks.ORCUS_STONE_BRICK_WALL.get())
                .add(ModBlocks.CRACKED_ORCUS_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_ORCUS_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_ORCUS_STONE_STAIRS.get())
                .add(ModBlocks.CHISELED_ORCUS_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_ORCUS_STONE.get())
                .add(ModBlocks.POLISHED_ORCUS_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_ORCUS_STONE_SLAB.get())
                .add(ModBlocks.ORCUS_PILLAR.get())
                .add(ModBlocks.ORCUS_RADIUM_ORE.get())
                .add(ModBlocks.ORCUS_COPPER_ORE.get())
                .add(ModBlocks.ORCUS_IRON_ORE.get())

                // Pluto
                .add(ModBlocks.PLUTONIUM_BLOCK.get())
                .add(ModBlocks.PLUTO_PLUTONIUM_ORE.get())
                .add(ModBlocks.RAW_PLUTONIUM_BLOCK.get())
                .add(ModBlocks.PLUTONIUM_PLATING.get())
                .add(ModBlocks.PLUTONIUM_PLATING_STAIRS.get())
                .add(ModBlocks.PLUTONIUM_PLATING_SLAB.get())
                .add(ModBlocks.PLUTONIUM_PILLAR.get())
                .add(ModBlocks.GLOWING_PLUTONIUM_PILLAR.get())
                .add(ModBlocks.PLUTONIUM_PLATING_BUTTON.get())
                .add(ModBlocks.PLUTONIUM_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.PLUTONIUM_SLIDING_DOOR.get())
                .add(ModBlocks.PLUTO_SAND.get())
                .add(ModBlocks.PLUTO_STONE.get())
                .add(ModBlocks.PLUTO_STONE_STAIRS.get())
                .add(ModBlocks.PLUTO_STONE_SLAB.get())
                .add(ModBlocks.PLUTO_COBBLESTONE.get())
                .add(ModBlocks.PLUTO_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.PLUTO_COBBLESTONE_SLAB.get())
                .add(ModBlocks.PLUTO_STONE_BRICKS.get())
                .add(ModBlocks.PLUTO_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.PLUTO_STONE_BRICK_SLAB.get())
                .add(ModBlocks.PLUTO_STONE_BRICK_WALL.get())
                .add(ModBlocks.CRACKED_PLUTO_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_PLUTO_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_PLUTO_STONE_STAIRS.get())
                .add(ModBlocks.CHISELED_PLUTO_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_PLUTO_STONE.get())
                .add(ModBlocks.POLISHED_PLUTO_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_PLUTO_STONE_SLAB.get())
                .add(ModBlocks.PLUTO_PILLAR.get())
                .add(ModBlocks.PLUTO_DIAMOND_ORE.get())
                .add(ModBlocks.PLUTO_GOLD_ORE.get())

                // Haumea
                .add(ModBlocks.HAUMEA_STONE.get())
                .add(ModBlocks.HAUMEA_STONE_STAIRS.get())
                .add(ModBlocks.HAUMEA_STONE_SLAB.get())
                .add(ModBlocks.HAUMEA_COBBLESTONE.get())
                .add(ModBlocks.HAUMEA_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.HAUMEA_COBBLESTONE_SLAB.get())
                .add(ModBlocks.HAUMEA_STONE_BRICKS.get())
                .add(ModBlocks.HAUMEA_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.HAUMEA_STONE_BRICK_SLAB.get())
                .add(ModBlocks.HAUMEA_STONE_BRICK_WALL.get())
                .add(ModBlocks.CRACKED_HAUMEA_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_HAUMEA_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_HAUMEA_STONE_STAIRS.get())
                .add(ModBlocks.CHISELED_HAUMEA_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_HAUMEA_STONE.get())
                .add(ModBlocks.POLISHED_HAUMEA_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_HAUMEA_STONE_SLAB.get())
                .add(ModBlocks.HAUMEA_PILLAR.get())
                .add(ModBlocks.HAUMEA_COPPER_ORE.get())
                .add(ModBlocks.HAUMEA_IRON_ORE.get())

                // Quaoar
                .add(ModBlocks.QUAOAR_STONE.get())
                .add(ModBlocks.QUAOAR_STONE_STAIRS.get())
                .add(ModBlocks.QUAOAR_STONE_SLAB.get())
                .add(ModBlocks.QUAOAR_COBBLESTONE.get())
                .add(ModBlocks.QUAOAR_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.QUAOAR_COBBLESTONE_SLAB.get())
                .add(ModBlocks.QUAOAR_STONE_BRICKS.get())
                .add(ModBlocks.QUAOAR_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.QUAOAR_STONE_BRICK_SLAB.get())
                .add(ModBlocks.QUAOAR_STONE_BRICK_WALL.get())
                .add(ModBlocks.CRACKED_QUAOAR_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_QUAOAR_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_QUAOAR_STONE_STAIRS.get())
                .add(ModBlocks.CHISELED_QUAOAR_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_QUAOAR_STONE.get())
                .add(ModBlocks.POLISHED_QUAOAR_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_QUAOAR_STONE_SLAB.get())
                .add(ModBlocks.QUAOAR_PILLAR.get())
                .add(ModBlocks.QUAOAR_COPPER_ORE.get())
                .add(ModBlocks.QUAOAR_IRON_ORE.get())

                // Makemake
                .add(ModBlocks.MAKEMAKE_STONE.get())
                .add(ModBlocks.MAKEMAKE_STONE_STAIRS.get())
                .add(ModBlocks.MAKEMAKE_STONE_SLAB.get())
                .add(ModBlocks.MAKEMAKE_COBBLESTONE.get())
                .add(ModBlocks.MAKEMAKE_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.MAKEMAKE_COBBLESTONE_SLAB.get())
                .add(ModBlocks.MAKEMAKE_STONE_BRICKS.get())
                .add(ModBlocks.MAKEMAKE_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.MAKEMAKE_STONE_BRICK_SLAB.get())
                .add(ModBlocks.MAKEMAKE_STONE_BRICK_WALL.get())
                .add(ModBlocks.CRACKED_MAKEMAKE_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_MAKEMAKE_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_MAKEMAKE_STONE_STAIRS.get())
                .add(ModBlocks.CHISELED_MAKEMAKE_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_MAKEMAKE_STONE.get())
                .add(ModBlocks.POLISHED_MAKEMAKE_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_MAKEMAKE_STONE_SLAB.get())
                .add(ModBlocks.MAKEMAKE_PILLAR.get())
                .add(ModBlocks.MAKEMAKE_COPPER_ORE.get())
                .add(ModBlocks.MAKEMAKE_IRON_ORE.get())

                // Gonggong
                .add(ModBlocks.GONGGONG_STONE.get())
                .add(ModBlocks.GONGGONG_STONE_STAIRS.get())
                .add(ModBlocks.GONGGONG_STONE_SLAB.get())
                .add(ModBlocks.GONGGONG_COBBLESTONE.get())
                .add(ModBlocks.GONGGONG_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.GONGGONG_COBBLESTONE_SLAB.get())
                .add(ModBlocks.GONGGONG_STONE_BRICKS.get())
                .add(ModBlocks.GONGGONG_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.GONGGONG_STONE_BRICK_SLAB.get())
                .add(ModBlocks.GONGGONG_STONE_BRICK_WALL.get())
                .add(ModBlocks.CRACKED_GONGGONG_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_GONGGONG_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_GONGGONG_STONE_STAIRS.get())
                .add(ModBlocks.CHISELED_GONGGONG_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_GONGGONG_STONE.get())
                .add(ModBlocks.POLISHED_GONGGONG_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_GONGGONG_STONE_SLAB.get())
                .add(ModBlocks.GONGGONG_PILLAR.get())
                .add(ModBlocks.GONGGONG_COPPER_ORE.get())
                .add(ModBlocks.GONGGONG_IRON_ORE.get())

                // Eris
                .add(ModBlocks.ERIS_STONE.get())
                .add(ModBlocks.ERIS_STONE_STAIRS.get())
                .add(ModBlocks.ERIS_STONE_SLAB.get())
                .add(ModBlocks.ERIS_COBBLESTONE.get())
                .add(ModBlocks.ERIS_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.ERIS_COBBLESTONE_SLAB.get())
                .add(ModBlocks.ERIS_STONE_BRICKS.get())
                .add(ModBlocks.ERIS_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.ERIS_STONE_BRICK_SLAB.get())
                .add(ModBlocks.ERIS_STONE_BRICK_WALL.get())
                .add(ModBlocks.CRACKED_ERIS_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_ERIS_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_ERIS_STONE_STAIRS.get())
                .add(ModBlocks.CHISELED_ERIS_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_ERIS_STONE.get())
                .add(ModBlocks.POLISHED_ERIS_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_ERIS_STONE_SLAB.get())
                .add(ModBlocks.ERIS_PILLAR.get())
                .add(ModBlocks.ERIS_COPPER_ORE.get())
                .add(ModBlocks.ERIS_IRON_ORE.get())

                // Sedna
                .add(ModBlocks.ELECTROLYTE_BLOCK.get())
                .add(ModBlocks.RAW_ELECTROLYTE_BLOCK.get())
                .add(ModBlocks.ELECTROLYTE_PLATING.get())
                .add(ModBlocks.ELECTROLYTE_PLATING_STAIRS.get())
                .add(ModBlocks.ELECTROLYTE_PLATING_SLAB.get())
                .add(ModBlocks.ELECTROLYTE_PILLAR.get())
                .add(ModBlocks.GLOWING_ELECTROLYTE_PILLAR.get())
                .add(ModBlocks.ELECTROLYTE_PLATING_BUTTON.get())
                .add(ModBlocks.ELECTROLYTE_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.ELECTROLYTE_SLIDING_DOOR.get())
                .add(ModBlocks.SEDNA_STONE.get())
                .add(ModBlocks.SEDNA_STONE_STAIRS.get())
                .add(ModBlocks.SEDNA_STONE_SLAB.get())
                .add(ModBlocks.SEDNA_COBBLESTONE.get())
                .add(ModBlocks.SEDNA_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.SEDNA_COBBLESTONE_SLAB.get())
                .add(ModBlocks.SEDNA_STONE_BRICKS.get())
                .add(ModBlocks.SEDNA_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.SEDNA_STONE_BRICK_SLAB.get())
                .add(ModBlocks.SEDNA_STONE_BRICK_WALL.get())
                .add(ModBlocks.CRACKED_SEDNA_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_SEDNA_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_SEDNA_STONE_STAIRS.get())
                .add(ModBlocks.CHISELED_SEDNA_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_SEDNA_STONE.get())
                .add(ModBlocks.POLISHED_SEDNA_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_SEDNA_STONE_SLAB.get())
                .add(ModBlocks.SEDNA_PILLAR.get())
                .add(ModBlocks.SEDNA_ELECTROLYTE_ORE.get())
                .add(ModBlocks.SEDNA_COPPER_ORE.get())
                .add(ModBlocks.SEDNA_IRON_ORE.get())

                // Proxima Centauri b
                .add(ModBlocks.B_SANDSTONE.get())
                .add(ModBlocks.B_SANDSTONE_BRICKS.get())
                .add(ModBlocks.B_SANDSTONE_BRICK_STAIRS.get())
                .add(ModBlocks.B_SANDSTONE_BRICK_SLAB.get())
                .add(ModBlocks.CRACKED_B_SANDSTONE_BRICKS.get())
                .add(ModBlocks.B_STONE.get())
                .add(ModBlocks.B_STONE_STAIRS.get())
                .add(ModBlocks.B_STONE_SLAB.get())
                .add(ModBlocks.B_COBBLESTONE.get())
                .add(ModBlocks.B_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.B_COBBLESTONE_SLAB.get())
                .add(ModBlocks.B_STONE_BRICKS.get())
                .add(ModBlocks.B_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.B_STONE_BRICK_SLAB.get())
                .add(ModBlocks.B_STONE_BRICK_WALL.get())
                .add(ModBlocks.CRACKED_B_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_B_STONE_BRICKS.get())
                .add(ModBlocks.CHISELED_B_STONE_STAIRS.get())
                .add(ModBlocks.CHISELED_B_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_B_STONE.get())
                .add(ModBlocks.POLISHED_B_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_B_STONE_SLAB.get())
                .add(ModBlocks.B_PILLAR.get())
                .add(ModBlocks.B_DIAMOND_ORE.get())
                .add(ModBlocks.B_EMERALD_ORE.get())
                .add(ModBlocks.B_IRON_ORE.get())
                .add(ModBlocks.B_REDSTONE_ORE.get());
        this.tag(BlockTags.MINEABLE_WITH_SHOVEL)
                .add(ModBlocks.JUPITER_SAND.get())
                .add(ModBlocks.CERES_SAND.get())
                .add(ModBlocks.SATURN_SAND.get())
                .add(ModBlocks.PLUTO_SAND.get())
                .add(ModBlocks.B_SAND.get())
                .add(ModBlocks.MOON_MYCELIUM.get());
        this.tag(BlockTags.DIAMOND_ORES)
                .add(ModBlocks.JUPITER_DIAMOND_ORE.get())
                .add(ModBlocks.SATURN_DIAMOND_ORE.get())
                .add(ModBlocks.URANUS_DIAMOND_ORE.get())
                .add(ModBlocks.PLUTO_DIAMOND_ORE.get())
                .add(ModBlocks.B_DIAMOND_ORE.get());
        this.tag(BlockTags.COAL_ORES)
                .add(ModBlocks.JUPITER_COAL_ORE.get())
                .add(ModBlocks.SATURN_COAL_ORE.get())
                .add(ModBlocks.NEPTUNE_COAL_ORE.get());
        this.tag(BlockTags.GOLD_ORES)
                .add(ModBlocks.JUPITER_GOLD_ORE.get())
                .add(ModBlocks.SATURN_GOLD_ORE.get())
                .add(ModBlocks.PLUTO_GOLD_ORE.get());
        this.tag(BlockTags.COPPER_ORES)
                .add(ModBlocks.CERES_COPPER_ORE.get())
                .add(ModBlocks.NEPTUNE_COPPER_ORE.get())
                .add(ModBlocks.ORCUS_COPPER_ORE.get())
                .add(ModBlocks.HAUMEA_COPPER_ORE.get())
                .add(ModBlocks.QUAOAR_COPPER_ORE.get())
                .add(ModBlocks.MAKEMAKE_COPPER_ORE.get())
                .add(ModBlocks.GONGGONG_COPPER_ORE.get())
                .add(ModBlocks.ERIS_COPPER_ORE.get())
                .add(ModBlocks.SEDNA_COPPER_ORE.get());
        this.tag(BlockTags.IRON_ORES)
                .add(ModBlocks.CERES_IRON_ORE.get())
                .add(ModBlocks.URANUS_IRON_ORE.get())
                .add(ModBlocks.NEPTUNE_IRON_ORE.get())
                .add(ModBlocks.ORCUS_IRON_ORE.get())
                .add(ModBlocks.HAUMEA_IRON_ORE.get())
                .add(ModBlocks.QUAOAR_IRON_ORE.get())
                .add(ModBlocks.MAKEMAKE_IRON_ORE.get())
                .add(ModBlocks.GONGGONG_IRON_ORE.get())
                .add(ModBlocks.ERIS_IRON_ORE.get())
                .add(ModBlocks.SEDNA_IRON_ORE.get())
                .add(ModBlocks.B_IRON_ORE.get());
        this.tag(BlockTags.LAPIS_ORES)
                .add(ModBlocks.URANUS_LAPIS_ORE.get());
        this.tag(BlockTags.EMERALD_ORES)
                .add(ModBlocks.B_EMERALD_ORE.get());
        this.tag(BlockTags.REDSTONE_ORES)
                .add(ModBlocks.B_REDSTONE_ORE.get());
        this.tag(BlockTags.SAND)
                .add(ModBlocks.JUPITER_SAND.get())
                .add(ModBlocks.CERES_SAND.get())
                .add(ModBlocks.SATURN_SAND.get())
                .add(ModBlocks.PLUTO_SAND.get())
                .add(ModBlocks.B_SAND.get());
        this.tag(BlockTags.ICE)
                .add(ModBlocks.SATURN_ICE.get())
                .add(ModBlocks.SLUSHY_ICE.get());
        this.tag(BlockTags.STAIRS)
                // Jupiter
                .add(ModBlocks.JUPERIUM_PLATING_STAIRS.get())
                .add(ModBlocks.JUPITER_STONE_STAIRS.get())
                .add(ModBlocks.JUPITER_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.JUPITER_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.CHISELED_JUPITER_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_JUPITER_STONE_STAIRS.get())

                // Ceres
                .add(ModBlocks.CERES_STONE_STAIRS.get())
                .add(ModBlocks.CERES_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.CERES_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.CHISELED_CERES_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_CERES_STONE_STAIRS.get())

                // Saturn
                .add(ModBlocks.SATURLYTE_PLATING_STAIRS.get())
                .add(ModBlocks.SATURN_STONE_STAIRS.get())
                .add(ModBlocks.SATURN_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.SATURN_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.CHISELED_SATURN_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_SATURN_STONE_STAIRS.get())

                // Uranus
                .add(ModBlocks.URANIUM_PLATING_STAIRS.get())
                .add(ModBlocks.URANUS_STONE_STAIRS.get())
                .add(ModBlocks.URANUS_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.URANUS_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.CHISELED_URANUS_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_URANUS_STONE_STAIRS.get())

                // Neptune
                .add(ModBlocks.NEPTUNIUM_PLATING_STAIRS.get())
                .add(ModBlocks.NEPTUNE_STONE_STAIRS.get())
                .add(ModBlocks.NEPTUNE_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.NEPTUNE_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.CHISELED_NEPTUNE_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_NEPTUNE_STONE_STAIRS.get())

                // Orcus
                .add(ModBlocks.RADIUM_PLATING_STAIRS.get())
                .add(ModBlocks.ORCUS_STONE_STAIRS.get())
                .add(ModBlocks.ORCUS_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.ORCUS_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.CHISELED_ORCUS_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_ORCUS_STONE_STAIRS.get())

                // Pluto
                .add(ModBlocks.PLUTONIUM_PLATING_STAIRS.get())
                .add(ModBlocks.PLUTO_STONE_STAIRS.get())
                .add(ModBlocks.PLUTO_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.PLUTO_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.CHISELED_PLUTO_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_PLUTO_STONE_STAIRS.get())

                // Haumea
                .add(ModBlocks.HAUMEA_STONE_STAIRS.get())
                .add(ModBlocks.HAUMEA_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.HAUMEA_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.CHISELED_HAUMEA_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_HAUMEA_STONE_STAIRS.get())

                // Quaoar
                .add(ModBlocks.QUAOAR_STONE_STAIRS.get())
                .add(ModBlocks.QUAOAR_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.QUAOAR_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.CHISELED_QUAOAR_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_QUAOAR_STONE_STAIRS.get())

                // Makemake
                .add(ModBlocks.MAKEMAKE_STONE_STAIRS.get())
                .add(ModBlocks.MAKEMAKE_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.MAKEMAKE_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.CHISELED_MAKEMAKE_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_MAKEMAKE_STONE_STAIRS.get())

                // Gonggong
                .add(ModBlocks.GONGGONG_STONE_STAIRS.get())
                .add(ModBlocks.GONGGONG_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.GONGGONG_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.CHISELED_GONGGONG_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_GONGGONG_STONE_STAIRS.get())

                // Eris
                .add(ModBlocks.ERIS_STONE_STAIRS.get())
                .add(ModBlocks.ERIS_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.ERIS_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.CHISELED_ERIS_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_ERIS_STONE_STAIRS.get())

                // Sedna
                .add(ModBlocks.ELECTROLYTE_PLATING_STAIRS.get())
                .add(ModBlocks.SEDNA_STONE_STAIRS.get())
                .add(ModBlocks.SEDNA_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.SEDNA_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.CHISELED_SEDNA_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_SEDNA_STONE_STAIRS.get())

                // Proxima Centauri b
                .add(ModBlocks.B_SANDSTONE_BRICK_STAIRS.get())
                .add(ModBlocks.B_STONE_STAIRS.get())
                .add(ModBlocks.B_COBBLESTONE_STAIRS.get())
                .add(ModBlocks.B_STONE_BRICK_STAIRS.get())
                .add(ModBlocks.CHISELED_B_STONE_STAIRS.get())
                .add(ModBlocks.POLISHED_B_STONE_STAIRS.get());
        this.tag(BlockTags.SLABS)
                // Jupiter
                .add(ModBlocks.JUPERIUM_PLATING_SLAB.get())
                .add(ModBlocks.JUPITER_STONE_SLAB.get())
                .add(ModBlocks.JUPITER_COBBLESTONE_SLAB.get())
                .add(ModBlocks.JUPITER_STONE_BRICK_SLAB.get())
                .add(ModBlocks.CHISELED_JUPITER_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_JUPITER_STONE_SLAB.get())

                // Ceres
                .add(ModBlocks.CERES_STONE_SLAB.get())
                .add(ModBlocks.CERES_COBBLESTONE_SLAB.get())
                .add(ModBlocks.CERES_STONE_BRICK_SLAB.get())
                .add(ModBlocks.CHISELED_CERES_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_CERES_STONE_SLAB.get())

                // Saturn
                .add(ModBlocks.SATURLYTE_PLATING_SLAB.get())
                .add(ModBlocks.SATURN_STONE_SLAB.get())
                .add(ModBlocks.SATURN_COBBLESTONE_SLAB.get())
                .add(ModBlocks.SATURN_STONE_BRICK_SLAB.get())
                .add(ModBlocks.CHISELED_SATURN_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_SATURN_STONE_SLAB.get())

                // Uranus
                .add(ModBlocks.URANIUM_PLATING_SLAB.get())
                .add(ModBlocks.URANUS_STONE_SLAB.get())
                .add(ModBlocks.URANUS_COBBLESTONE_SLAB.get())
                .add(ModBlocks.URANUS_STONE_BRICK_SLAB.get())
                .add(ModBlocks.CHISELED_URANUS_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_URANUS_STONE_SLAB.get())

                // Neptune
                .add(ModBlocks.NEPTUNIUM_PLATING_SLAB.get())
                .add(ModBlocks.NEPTUNE_STONE_SLAB.get())
                .add(ModBlocks.NEPTUNE_COBBLESTONE_SLAB.get())
                .add(ModBlocks.NEPTUNE_STONE_BRICK_SLAB.get())
                .add(ModBlocks.CHISELED_NEPTUNE_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_NEPTUNE_STONE_SLAB.get())

                // Orcus
                .add(ModBlocks.RADIUM_PLATING_SLAB.get())
                .add(ModBlocks.ORCUS_STONE_SLAB.get())
                .add(ModBlocks.ORCUS_COBBLESTONE_SLAB.get())
                .add(ModBlocks.ORCUS_STONE_BRICK_SLAB.get())
                .add(ModBlocks.CHISELED_ORCUS_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_ORCUS_STONE_SLAB.get())

                // Pluto
                .add(ModBlocks.PLUTONIUM_PLATING_SLAB.get())
                .add(ModBlocks.PLUTO_STONE_SLAB.get())
                .add(ModBlocks.PLUTO_COBBLESTONE_SLAB.get())
                .add(ModBlocks.PLUTO_STONE_BRICK_SLAB.get())
                .add(ModBlocks.CHISELED_PLUTO_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_PLUTO_STONE_SLAB.get())

                // Haumea
                .add(ModBlocks.HAUMEA_STONE_SLAB.get())
                .add(ModBlocks.HAUMEA_COBBLESTONE_SLAB.get())
                .add(ModBlocks.HAUMEA_STONE_BRICK_SLAB.get())
                .add(ModBlocks.CHISELED_HAUMEA_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_HAUMEA_STONE_SLAB.get())

                // Quaoar
                .add(ModBlocks.QUAOAR_STONE_SLAB.get())
                .add(ModBlocks.QUAOAR_COBBLESTONE_SLAB.get())
                .add(ModBlocks.QUAOAR_STONE_BRICK_SLAB.get())
                .add(ModBlocks.CHISELED_QUAOAR_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_QUAOAR_STONE_SLAB.get())

                // Makemake
                .add(ModBlocks.MAKEMAKE_STONE_SLAB.get())
                .add(ModBlocks.MAKEMAKE_COBBLESTONE_SLAB.get())
                .add(ModBlocks.MAKEMAKE_STONE_BRICK_SLAB.get())
                .add(ModBlocks.CHISELED_MAKEMAKE_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_MAKEMAKE_STONE_SLAB.get())

                // Gonggong
                .add(ModBlocks.GONGGONG_STONE_SLAB.get())
                .add(ModBlocks.GONGGONG_COBBLESTONE_SLAB.get())
                .add(ModBlocks.GONGGONG_STONE_BRICK_SLAB.get())
                .add(ModBlocks.CHISELED_GONGGONG_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_GONGGONG_STONE_SLAB.get())

                // Eris
                .add(ModBlocks.ERIS_STONE_SLAB.get())
                .add(ModBlocks.ERIS_COBBLESTONE_SLAB.get())
                .add(ModBlocks.ERIS_STONE_BRICK_SLAB.get())
                .add(ModBlocks.CHISELED_ERIS_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_ERIS_STONE_SLAB.get())

                // Sedna
                .add(ModBlocks.ELECTROLYTE_PLATING_SLAB.get())
                .add(ModBlocks.SEDNA_STONE_SLAB.get())
                .add(ModBlocks.SEDNA_COBBLESTONE_SLAB.get())
                .add(ModBlocks.SEDNA_STONE_BRICK_SLAB.get())
                .add(ModBlocks.CHISELED_SEDNA_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_SEDNA_STONE_SLAB.get())

                // Proxima Centauri b
                .add(ModBlocks.B_SANDSTONE_BRICK_SLAB.get())
                .add(ModBlocks.B_STONE_SLAB.get())
                .add(ModBlocks.B_COBBLESTONE_SLAB.get())
                .add(ModBlocks.B_STONE_BRICK_SLAB.get())
                .add(ModBlocks.CHISELED_B_STONE_SLAB.get())
                .add(ModBlocks.POLISHED_B_STONE_SLAB.get());
        this.tag(BlockTags.WALLS)
                .add(ModBlocks.JUPITER_STONE_BRICK_WALL.get())
                .add(ModBlocks.CERES_STONE_BRICK_WALL.get())
                .add(ModBlocks.SATURN_STONE_BRICK_WALL.get())
                .add(ModBlocks.URANUS_STONE_BRICK_WALL.get())
                .add(ModBlocks.NEPTUNE_STONE_BRICK_WALL.get())
                .add(ModBlocks.ORCUS_STONE_BRICK_WALL.get())
                .add(ModBlocks.PLUTO_STONE_BRICK_WALL.get())
                .add(ModBlocks.HAUMEA_STONE_BRICK_WALL.get())
                .add(ModBlocks.QUAOAR_STONE_BRICK_WALL.get())
                .add(ModBlocks.MAKEMAKE_STONE_BRICK_WALL.get())
                .add(ModBlocks.GONGGONG_STONE_BRICK_WALL.get())
                .add(ModBlocks.ERIS_STONE_BRICK_WALL.get())
                .add(ModBlocks.SEDNA_STONE_BRICK_WALL.get())
                .add(ModBlocks.B_STONE_BRICK_WALL.get());
        this.tag(BlockTags.BUTTONS)
                .add(ModBlocks.JUPERIUM_PLATING_BUTTON.get())
                .add(ModBlocks.SATURLYTE_PLATING_BUTTON.get())
                .add(ModBlocks.URANIUM_PLATING_BUTTON.get())
                .add(ModBlocks.NEPTUNIUM_PLATING_BUTTON.get())
                .add(ModBlocks.RADIUM_PLATING_BUTTON.get())
                .add(ModBlocks.PLUTONIUM_PLATING_BUTTON.get())
                .add(ModBlocks.ELECTROLYTE_PLATING_BUTTON.get());
        this.tag(BlockTags.PRESSURE_PLATES)
                .add(ModBlocks.JUPERIUM_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.SATURLYTE_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.URANIUM_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.NEPTUNIUM_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.RADIUM_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.PLUTONIUM_PLATING_PRESSURE_PLATE.get())
                .add(ModBlocks.ELECTROLYTE_PLATING_PRESSURE_PLATE.get());
        this.tag(Tags.Blocks.STORAGE_BLOCKS)
                .addTag(ModBlockTags.JUPERIUM_BLOCKS)
                .addTag(ModBlockTags.SATURLYTE_BLOCKS)
                .addTag(ModBlockTags.URANIUM_BLOCKS)
                .addTag(ModBlockTags.NEPTUNIUM_BLOCKS)
                .addTag(ModBlockTags.RADIUM_BLOCKS)
                .addTag(ModBlockTags.PLUTONIUM_BLOCKS)
                .addTag(ModBlockTags.ELECTROLYTE_BLOCKS);
        this.tag(BlockTags.STANDING_SIGNS)
                .add(ModBlocks.AERONOS_SIGN.get())
                .add(ModBlocks.STROPHAR_SIGN.get());
        this.tag(BlockTags.WALL_SIGNS)
                .add(ModBlocks.AERONOS_WALL_SIGN.get())
                .add(ModBlocks.STROPHAR_WALL_SIGN.get());
        this.tag(BlockTags.CEILING_HANGING_SIGNS)
                .add(ModBlocks.GLACIAN_HANGING_SIGN.get())
                .add(ModBlocks.AERONOS_HANGING_SIGN.get())
                .add(ModBlocks.STROPHAR_HANGING_SIGN.get());
        this.tag(BlockTags.WALL_HANGING_SIGNS)
                .add(ModBlocks.GLACIAN_WALL_HANGING_SIGN.get())
                .add(ModBlocks.AERONOS_WALL_HANGING_SIGN.get())
                .add(ModBlocks.STROPHAR_WALL_HANGING_SIGN.get());
        this.tag(Tags.Blocks.ORES)
                .addTag(ModBlockTags.JUPERIUM_ORES)
                .addTag(ModBlockTags.SATURLYTE_ORES)
                .addTag(ModBlockTags.URANIUM_ORES)
                .addTag(ModBlockTags.NEPTUNIUM_ORES)
                .addTag(ModBlockTags.RADIUM_ORES)
                .addTag(ModBlockTags.PLUTONIUM_ORES)
                .addTag(ModBlockTags.ELECTROLYTE_ORES);
        this.tag(ModBlockTags.JUPERIUM_BLOCKS)
                .add(ModBlocks.JUPERIUM_BLOCK.get());
        this.tag(ModBlockTags.JUPERIUM_ORES)
                .add(ModBlocks.JUPITER_JUPERIUM_ORE.get());
        this.tag(ModBlockTags.ICE_SHARD_ORES)
                .add(ModBlocks.URANUS_ICE_SHARD_ORE.get());
        this.tag(ModBlockTags.SATURLYTE_BLOCKS)
                .add(ModBlocks.SATURLYTE_BLOCK.get());
        this.tag(ModBlockTags.SATURLYTE_ORES)
                .add(ModBlocks.SATURN_SATURLYTE_ORE.get());
        this.tag(ModBlockTags.URANIUM_BLOCKS)
                .add(ModBlocks.URANIUM_BLOCK.get());
        this.tag(ModBlockTags.URANIUM_ORES)
                .add(ModBlocks.URANUS_URANIUM_ORE.get());
        this.tag(ModBlockTags.NEPTUNIUM_BLOCKS)
                .add(ModBlocks.NEPTUNIUM_BLOCK.get());
        this.tag(ModBlockTags.NEPTUNIUM_ORES)
                .add(ModBlocks.NEPTUNE_NEPTUNIUM_ORE.get());
        this.tag(ModBlockTags.RADIUM_BLOCKS)
                .add(ModBlocks.RADIUM_BLOCK.get());
        this.tag(ModBlockTags.RADIUM_ORES)
                .add(ModBlocks.ORCUS_RADIUM_ORE.get());
        this.tag(ModBlockTags.PLUTONIUM_BLOCKS)
                .add(ModBlocks.PLUTONIUM_BLOCK.get());
        this.tag(ModBlockTags.PLUTONIUM_ORES)
                .add(ModBlocks.PLUTO_PLUTONIUM_ORE.get());
        this.tag(ModBlockTags.ELECTROLYTE_BLOCKS)
                .add(ModBlocks.ELECTROLYTE_BLOCK.get());
        this.tag(ModBlockTags.ELECTROLYTE_ORES)
                .add(ModBlocks.SEDNA_ELECTROLYTE_ORE.get());
        this.tag(BlockTags.BEACON_BASE_BLOCKS)
                .add(ModBlocks.JUPERIUM_BLOCK.get())
                .add(ModBlocks.SATURLYTE_BLOCK.get())
                .add(ModBlocks.URANIUM_BLOCK.get())
                .add(ModBlocks.NEPTUNIUM_BLOCK.get())
                .add(ModBlocks.RADIUM_BLOCK.get())
                .add(ModBlocks.PLUTONIUM_BLOCK.get())
                .add(ModBlocks.ELECTROLYTE_BLOCK.get());
        this.tag(Tags.Blocks.STONE)
                .add(ModBlocks.CERES_STONE.get())
                .add(ModBlocks.JUPITER_STONE.get())
                .add(ModBlocks.SATURN_STONE.get())
                .add(ModBlocks.URANUS_STONE.get())
                .add(ModBlocks.NEPTUNE_STONE.get())
                .add(ModBlocks.ORCUS_STONE.get())
                .add(ModBlocks.PLUTO_STONE.get())
                .add(ModBlocks.HAUMEA_STONE.get())
                .add(ModBlocks.QUAOAR_STONE.get())
                .add(ModBlocks.MAKEMAKE_STONE.get())
                .add(ModBlocks.GONGGONG_STONE.get())
                .add(ModBlocks.ERIS_STONE.get())
                .add(ModBlocks.SEDNA_STONE.get())
                .add(ModBlocks.B_STONE.get());
        this.tag(Tags.Blocks.SANDSTONE)
                .add(ModBlocks.B_SANDSTONE.get());
        this.tag(BlockTags.SAPLINGS)
                .add(ModBlocks.GLACIAN_SAPLING.get());
        this.tag(BlockTags.DOORS)
                .add(ModBlocks.JUPERIUM_SLIDING_DOOR.get())
                .add(ModBlocks.SATURLYTE_SLIDING_DOOR.get())
                .add(ModBlocks.URANIUM_SLIDING_DOOR.get())
                .add(ModBlocks.NEPTUNIUM_SLIDING_DOOR.get())
                .add(ModBlocks.RADIUM_SLIDING_DOOR.get())
                .add(ModBlocks.PLUTONIUM_SLIDING_DOOR.get())
                .add(ModBlocks.ELECTROLYTE_SLIDING_DOOR.get());
        this.tag(BlockTags.MUSHROOM_GROW_BLOCK)
                .add(ModBlocks.MOON_MYCELIUM.get());
    }
}
